using BookRepositoryApi.Models;
using BookRepositoryApi.Models.Auth;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace BookRepositoryApi.Data.Configurations;

public class BookConfiguration : IEntityTypeConfiguration<Book>
{
    public void Configure(EntityTypeBuilder<Book> builder)
    {
        builder.HasKey(b => b.Id);
        // configure numeric ID to be generated by the database on add
        builder.Property(b => b.Id)
              .ValueGeneratedOnAdd();

        builder.Property(b => b.Title).HasMaxLength(200).IsRequired();
        builder.Property(b => b.Author).HasMaxLength(120).IsRequired();
        builder.Property(b => b.Isbn).HasMaxLength(20).IsRequired();

        // relationship to the user who created the book
        builder.Property(b => b.AuthorId).IsRequired();
        builder.HasOne(b => b.AuthorUser)
              .WithMany(u => u.Books)
              .HasForeignKey(b => b.AuthorId)
              .OnDelete(DeleteBehavior.Cascade);
    }
}
