using BookRepositoryApi.Models;
using BookRepositoryApi.Models.Auth;
using Microsoft.EntityFrameworkCore;

namespace BookRepositoryApi.Data;
public class AppDbContext : DbContext
{
    public AppDbContext(DbContextOptions<AppDbContext> options) : base(options)
    {
    }

    public DbSet<Book> Books { get; set; }
    public DbSet<AppUser> Users { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Book>(entity =>
        {
            entity.HasKey(b => b.Id);
            // configure numeric ID to be generated by the database on add
            entity.Property(b => b.Id)
                  .ValueGeneratedOnAdd();

            entity.Property(b => b.Title).HasMaxLength(200).IsRequired();
            entity.Property(b => b.Author).HasMaxLength(120).IsRequired();
            entity.Property(b => b.Isbn).HasMaxLength(20).IsRequired();
        });

        modelBuilder.Entity<AppUser>(entity =>
        {
            entity.HasKey(u => u.Id);
            entity.Property(u => u.Id)
                  .ValueGeneratedOnAdd();
            entity.Property(u => u.Username).HasMaxLength(64).IsRequired();
            entity.Property(u => u.NormalizedUsername).HasMaxLength(64).IsRequired();
            entity.Property(u => u.Role).HasMaxLength(32).IsRequired();
            entity.Property(u => u.PasswordHash).IsRequired();
            entity.HasIndex(u => u.NormalizedUsername).IsUnique();
        });
    }
}
